security:
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'
    providers:
        user_provider:
            id: App\Security\Provider\UserProvider
        app_provider:
            id: App\Security\Provider\AppProvider
        jwt_provider:
            id: App\Security\Provider\JWTProvider

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        admin:
            pattern: ^/admin
            provider: user_provider
            logout:
                path: app_logout
                target: app_login
            form_login:
                login_path: app_login
                check_path: app_login
        auth:
            pattern: ^/api/auth
            stateless: true
            lazy: true
            provider: app_provider
            json_login:
                check_path: app_login_check
                success_handler: App\Security\Handler\AuthSuccessHandler
                failure_handler: App\Security\Handler\AuthFailureHandler
                username_path: data.key
                password_path: data.secret
            custom_authenticators:
                - App\Security\Guard\AppAuthenticator
            logout:
                path: /api/logout
        api:
            pattern: ^/api
            provider: jwt_provider
            custom_authenticators:
                - App\Security\Guard\TokenAuthenticator
            logout:
                path: /v3/logout

    access_control:
         - { path: '^/api/product/on-sale', roles: PUBLIC_ACCESS, methods: [GET] }
         - { path: '^/api/(product|category)/\d+$', roles: PUBLIC_ACCESS, methods: [GET] }
         - { path: '^/admin/login', roles: PUBLIC_ACCESS }
         - { path: '^/admin', roles: ROLE_ADMIN }
         - { path: '^/api', roles: ROLE_APP }
         - { path: '^/', roles: IS_AUTHENTICATED_FULLY }

when@test:
    security:
        password_hashers:
            Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface:
                algorithm: auto
                cost: 4 # Lowest possible value for bcrypt
                time_cost: 3 # Lowest possible value for argon
                memory_cost: 10 # Lowest possible value for argon
